### ISSUE TITLE
Include theme stylesheets

### ISSUE THREAD

**Issue by cranst0n** [webjars/angular-material#7]
The angular-material project provides a set of themed CSS files that you can override colors with (e.g. `green-theme.css`). They're located in the `themes` directory.

Including this directory of individual files would be helpful but I don't known enough about the `pom.xml` syntax to create a pull request.

**Comment by njacobs5074** [comment]
I've installed webjar 0.8.0 of angular-material and I don't see the full set of Angular Material CSS files.  Issue raised by @cranst0n seems to still be present.

**Comment by jamesward** [comment]
It looks like we intentionally exclude the `modules` dir.  Is that where the stuff you need is?  I'm not sure why exactly we exclude that.

**Comment by cranst0n** [comment]
Since I raised the issue, they've switched to configuring themes via an [Angular service](https://material.angularjs.org/#/Theming/03_configuring_a_theme) so the CSS theme files are no more. You should just need the `angular-material.css` file.

**Comment by njacobs5074** [comment]
So I see.  @cranst0n: Thanks for looking into this - very helpful.

Nick
